// Generated by CoffeeScript 1.4.0
(function() {

  $.fn.extend({
    parallax: function() {
      var ratio, scroll_top, self;
      scroll_top = $(window).scrollTop();
      self = $(this);
      ratio = parseFloat(self.data('parallax-background-ratio'));
      return self.css('background-position', "0 " + (scroll_top * ratio) + "px");
    }
  });

  $('#to-top').click(function() {
    return $("html,body").animate({
      scrollTop: $("#top").offset().top
    }, 500);
  });

  $(window).scroll(function() {
    var scroll_top;
    $('#home').parallax();
    scroll_top = $(window).scrollTop();
    if (scroll_top > 0) {
      $('#to-top').css('opacity', 1);
    } else {
      $('#to-top').css('opacity', '0');
    }
    return $("#footer-sns #weixin").poshytip({
      className: 'tip-twitter',
      showTimeout: 1,
      alignTo: 'target',
      alignX: 'center'
    });
  });

}).call(this);
