// Generated by CoffeeScript 1.4.0
(function() {
  var pathname;

  $.fn.extend({
    parallax: function() {
      var ratio, scroll_top, self;
      scroll_top = $(window).scrollTop();
      self = $(this);
      ratio = parseFloat(self.data('parallax-background-ratio'));
      return self.css('background-position', "center " + (scroll_top * ratio) + "px");
    }
  });

  $('.to-top').click(function() {
    return $("html,body").animate({
      scrollTop: $("#top").offset().top - 60
    }, 500);
  });

  $(window).scroll(function() {});

  $("#footer-sns #weixin").poshytip({
    className: 'tip-twitter',
    alignTo: 'target',
    alignX: 'center'
  });

  pathname = location.pathname;

  $("#navbar>ul>li").removeClass('active');

  $("#navbar>ul>li").each(function() {
    var self;
    self = $(this);
    if (self.children("a").attr('href') === pathname) {
      return self.addClass('active');
    }
  });

  window.def_view = function(module, ctrl, fun) {
    var app;
    app = angular.module(module, ["ngSanitize"]).controller(ctrl, fun);
    app.filter('deal_str', function() {
      return $.deal_str;
    });
    return app;
  };

  $.postJSON = function(url, data, callback) {
    return $.ajax({
      url: url,
      data: data,
      type: 'post',
      success: callback
    });
  };

  $.deal_str = function(str) {
    var r;
    r = new RegExp('>', 'g');
    str = str.replace(r, '&gt;');
    r = new RegExp('<', 'g');
    str = str.replace(r, '&lt;');
    str = str.replace(/\n/g, "</p><p>");
    return "<p>" + str + "</p>";
  };

}).call(this);
