// Generated by CoffeeScript 1.4.0
(function() {

  window.CONST = window.CONST || {};

  CONST.HOST = 'http://c.cc:8080';

  CONST.ENUM = CONST.ENUM || {};

  CONST.ENUM.BLOOD = {
    'A': 20,
    'B': 30,
    'AB': 40,
    'O': 10
  };

  CONST.ENUM.DEGREE = {
    'BACHELOR': 20,
    'MASTER': 30,
    'DIPLOMA': 10,
    'PHD': 40
  };

}).call(this);
