// Generated by CoffeeScript 1.4.0
(function() {
  var STATIC_HOST;

  window.CONST = window.CONST || {};

  CONST.HOST = 'http://c.cc:8080';

  STATIC_HOST = 'http://static.c.cc:8080';

}).call(this);
