// Generated by CoffeeScript 1.9.3
(function() {
  var pathname;

  pathname = location.pathname;

  $("#header #menu ul li").removeClass('active');

  $("#header #menu ul li").each(function() {
    var self;
    self = $(this);
    if (self.children("a").attr('href') === pathname) {
      return self.addClass('active');
    }
  });

}).call(this);
