// Generated by CoffeeScript 1.9.3
(function() {
  def_view('RegApp', 'RegCtrl', function($scope) {
    var o;
    o = {};
    o.name = '1';
    o.startup_name = '2';
    o.phone = '3';
    o.email = '4';
    o.desc = '5';
    $scope.o = o;
    return $scope.submit = function() {
      return $.postJSON('/j/reg', $scope.o, function(o) {});
    };
  });

}).call(this);
