// Generated by CoffeeScript 1.4.0
(function() {

  def_view('LoginApp', 'LoginCtrl', function($scope) {
    var o;
    o = {};
    o.user_name = '';
    o.password = '';
    $scope.o = o;
    return $scope.submit = function() {
      return $.postJSON('/j/login', $scope.o, function(o) {
        return window.location.href = '/';
      });
    };
  });

}).call(this);
