// Generated by CoffeeScript 1.4.0
(function() {
  var editor;

  def_view('NewsApp', 'NewsCtrl', function($scope) {
    var o;
    o = {
      title: '',
      summary: '',
      img: '',
      content: ''
    };
    $scope.o = o;
    $scope.percent = 0;
    return $scope.submit = function() {
      return $.postJSON('/j/admin/add_news', $scope.o, function(o) {
        return $.alert_success('保存成功');
      });
    };
  });

  editor = new Simditor({
    upload: {
      fileKey: 'file',
      url: 'http://up.qiniu.com/',
      params: {
        "token": "/j/upload_token"
      }
    },
    textarea: $('#content')
  });

  $('#img_up').uploader({
    uploading: function(percent) {
      V().percent = percent;
      V().$apply();
      if (percent === 100) {
        return percent = 0;
      }
    },
    uploaded: function(id, url) {
      V().o.img = id;
      V().$apply();
      $('#img-preview').css('background-image', "url(" + url + "?imageView2/1/w/436/h/436)");
      return $('#img-preview').addClass('preview');
    },
    error: function(up, err, errTip) {
      return console.log(errTip);
    }
  });

}).call(this);
