// Generated by CoffeeScript 1.4.0
(function() {

  def_view('LoginApp', 'LoginCtrl', function($scope) {
    var o;
    o = {};
    o.user_name = 'tonghs';
    o.password = 'tonghs';
    $scope.o = o;
    return $scope.submit = function() {
      return $.postJSON('/j/admin/login', $scope.o, function(o) {
        if (o.success) {
          return window.location.href = '/admin/index';
        } else {
          return alert(o.msg);
        }
      });
    };
  });

}).call(this);
