// Generated by CoffeeScript 1.9.3
(function() {
  $('.del').click(function() {
    var self;
    self = $(this);
    return $.confirm(function() {
      var id;
      id = self.data('id');
      return $.postJSON('/j/admin/del_report', {
        id_: id
      }, function(o) {
        return location.reload();
      });
    }, '确定删除吗？');
  });

}).call(this);
