// Generated by CoffeeScript 1.9.3
(function() {
  window.def_settings_view = function(o) {
    return def_view('SettingsApp', 'SettingsCtrl', function($scope) {
      $scope.o = o;
      return $scope.submit = function() {
        return $.postJSON('/j/admin/settings', $scope.o, function(o) {
          return $.alert_success('保存成功');
        });
      };
    });
  };

}).call(this);
