// Generated by CoffeeScript 1.4.0
(function() {

  window.def_settings_view = function(o) {
    return def_view('SettingsApp', 'SettingsCtrl', function($scope) {
      $scope.o = o;
      return $scope.submit = function() {
        return $.postJSON('', $scope.o, function(o) {
          return window.location.href = '/reg_success';
        });
      };
    });
  };

}).call(this);
